name = "rizipt-v2-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "rizipt_v2"
database_id = "ff303f78-3914-4d09-a2bb-2a21c05e368a"

[vars]
ALLOWED_ORIGIN = "https://rizipt.in"
